services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
#    image: ghcr.io/ivellios/jewel:latest
    build:
      dockerfile: ./docker/dev.Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - venv:/app/.venv
    command: >
      sh -c "uv run manage.py migrate &&
             uv run manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  venv:
