# Generated by Django 4.1.1 on 2022-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SteamGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appid", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
