# Generated by Django 4.1.1 on 2025-09-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("games", "0002_remove_game_title_game_name"),
        ("games", "0003_alter_game_name"),
    ]

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="title",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Game title"),
        ),
    ]
