# Generated by Django 4.1.1 on 2025-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_remove_game_title_game_name_squashed_0003_alter_game_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameonplatform",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="gameonplatform",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
