# Generated by Django 4.1.1 on 2022-10-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_gameonplatform_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="added",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.ManyToManyField(blank=True, null=True, to="games.genre"),
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="games",
                through="games.GameOnPlatform",
                to="games.platform",
                verbose_name="Platform",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Purchase price",
            ),
        ),
    ]
