# Generated by Django 4.1.1 on 2025-09-02 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_add_soft_delete_to_gameonplatform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameonplatform",
            old_name="source",
            new_name="vendor",
        ),
    ]
