# Generated by Django 4.1.1 on 2022-10-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_added_alter_game_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameonplatform",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platforms_meta_data",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gameonplatform",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_meta_data",
                to="games.platform",
            ),
        ),
    ]
