# Generated by Django 5.2.5 on 2026-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_rename_source_to_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameonplatform",
            name="added",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="gameonplatform",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=6,
                null=True,
                verbose_name="Purchase price",
            ),
        ),
    ]
