# Generated by Django 4.1.1 on 2022-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_gameonplatform_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
