# Generated by Django 4.1.1 on 2022-10-01 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
