# Generated by Django 5.2.5 on 2026-01-24 12:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_alter_gameonplatform_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameonplatform",
            name="added",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
