# Generated by Django 4.1.1 on 2022-10-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_game_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="genre",
            new_name="genres",
        ),
    ]
