# Generated by Django 4.1.1 on 2022-10-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_alter_game_controller_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="party_fit",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
