# Generated by Django 4.1.1 on 2022-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_alter_game_party_fit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(blank=True, to="games.genre"),
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(
                blank=True,
                related_name="games",
                through="games.GameOnPlatform",
                to="games.platform",
                verbose_name="Platform",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="played",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Already Played"
            ),
        ),
    ]
